version: 2
builds:
  - id: isapex
    main: ./isapex
    binary: isapex
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -extldflags=-static
    env:
      - CGO_ENABLED=0
    hooks:
      post:
        - cmd: upx --best --lzma {{ .Path }}
  - id: wappalyzator
    main: ./wappalyzator
    binary: wappalyzator
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -extldflags=-static
    env:
      - CGO_ENABLED=0
    hooks:
      post:
        - cmd: upx --best --lzma {{ .Path }}
  - id: test
    main: ./test
    binary: test
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -extldflags=-static
    env:
      - CGO_ENABLED=0
    hooks:
      post:
        - cmd: upx --best --lzma {{ .Path }}
release:
  github:
    owner: ducksify
    name: panop-tools
