name: 'Build and Test'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      skip_macos:
        description: 'Skip macOS builds'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      -
        name: Install UPX
        run: |
          wget https://github.com/upx/upx/releases/download/v4.0.2/upx-4.0.2-amd64_linux.tar.xz
          tar -xf upx-4.0.2-amd64_linux.tar.xz
          sudo mv upx-4.0.2-amd64_linux/upx /usr/local/bin/
          rm -rf upx-4.0.2-amd64_linux*
      -
        name: Test Build with UPX
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: build --snapshot --clean --config .goreleaser.yaml
      -
        name: Show Build Summary
        run: |
          echo "=== Binary Sizes ==="
          ls -lah dist/*/
          echo ""
          echo "=== Total Size ==="
          du -sh dist/
      -
        name: Test wappalyzator binary
        run: |
          echo "Testing wappalyzator binary..."
          ./dist/wappalyzator_linux_amd64_v1/wappalyzator https://www.google.com
